#! /bin/sh

summary_files=$(ls -1 $1 | sed -n -e 's/^\([[:digit:]]\{8\}\)\([[:digit:]]\{4\}\)\([NS]\)\(..\)\(.*\)/\1_\3\5/p' | sort | uniq)

for f in $summary_files; do
   d=${f%_?.gif}
   e=${f#${d}_}
   h=${e%.gif}
#   echo $d, $e, $h
   echo ": images/$d*$h*.gif |>   !montage    |>  composite-$f"
done

