#! /bin/sh

files=$(ls -1 $1 | sed -n -e 's/^\([[:digit:]]\{8\}\)\([[:digit:]]\{4\}\)\([NS]\)\(..\)\(.*\)/\1_\3\5/p' | sort | uniq)

for f in $files; do
   d=${f%_?.gif}
   e=${f#${d}_}
   h=${e%.gif}
#   echo $d, $e, $h
   echo ": images/$d*$h*.gif |>   montage -label \"%%f\" -geometry 160x160+4+4 -tile 7x  %f  $f   |>  $f"
done

